name: check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: install luarocks
        run: sudo apt-get install luarocks
      - name: download luacheck
        uses: actions/checkout@master
        with:
          repository: lunarmodules/luacheck
          path: luacheck
      - name: build luacheck
        run: |
          cd luacheck
          sudo luarocks make
          cd ..
      - run: cd sailing_kit
      - name: run luacheck
        run: luacheck .
      - name: install stylua
        run: cargo install stylua
      - name: run stylua
        run: stylua .
        
