name: check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: install luarocks
        run: sudo apt-get install luarocks
      - name: install stylua
        run: sudo luarocks install stylua
      - name: run stylua
        run: stylua .
        
